// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqzXNfRJ1WhSvDkwFOESl54CZS76_Rnug',
    appId: '1:995751723070:web:5908e0327ab40b4120516f',
    messagingSenderId: '995751723070',
    projectId: 'offpay10',
    authDomain: 'offpay10.firebaseapp.com',
    storageBucket: 'offpay10.firebasestorage.app',
    measurementId: 'G-HHKWGR1T9D',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdGD0t9eg-9_osO1w9NaYel64sszTgtuY',
    appId: '1:995751723070:ios:42597939030b6d9620516f',
    messagingSenderId: '995751723070',
    projectId: 'offpay10',
    storageBucket: 'offpay10.firebasestorage.app',
    iosBundleId: 'com.example.offpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqzXNfRJ1WhSvDkwFOESl54CZS76_Rnug',
    appId: '1:995751723070:web:71b08ba114fbac2120516f',
    messagingSenderId: '995751723070',
    projectId: 'offpay10',
    authDomain: 'offpay10.firebaseapp.com',
    storageBucket: 'offpay10.firebasestorage.app',
    measurementId: 'G-EFYHEZBQVN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdGD0t9eg-9_osO1w9NaYel64sszTgtuY',
    appId: '1:995751723070:ios:42597939030b6d9620516f',
    messagingSenderId: '995751723070',
    projectId: 'offpay10',
    storageBucket: 'offpay10.firebasestorage.app',
    iosBundleId: 'com.example.offpay',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7K3NVQwuy9RyMeQ0tVr-S4K0SMa4t7ig',
    appId: '1:995751723070:android:266eab5a5f49d28420516f',
    messagingSenderId: '995751723070',
    projectId: 'offpay10',
    storageBucket: 'offpay10.firebasestorage.app',
  );

}